In [5]:
import pandas as pd

import sklearn

In [6]:
from sklearn.datasets import fetch_california_housing

data = fetch_california_housing()
X = data.data
y = data.target

print(X.shape, y.shape)


(20640, 8) (20640,)


In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
import pandas as pd

url = "https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv"
df = pd.read_csv(url)

df


crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [9]:
dff=pd.DataFrame(df)

In [10]:
dff

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [11]:
dff.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')

In [12]:

 from sklearn.model_selection import train_test_split  


In [13]:
 X_train, X_test, y_train, y_test = train_test_split(  
   X, y, test_size=0.33, random_state=42) 

In [14]:
X_train

array([[   0.9809    ,   19.        ,    3.18772563, ...,    2.62093863,
          33.98      , -118.28      ],
       [   4.2232    ,   33.        ,    6.18969555, ...,    2.37704918,
          37.46      , -122.23      ],
       [   3.5488    ,   42.        ,    4.82157676, ...,    4.33195021,
          33.79      , -118.26      ],
       ...,
       [   2.9344    ,   36.        ,    3.98671727, ...,    3.33206831,
          34.03      , -118.38      ],
       [   5.7192    ,   15.        ,    6.39534884, ...,    3.17889088,
          37.58      , -121.96      ],
       [   2.5755    ,   52.        ,    3.40257649, ...,    2.10869565,
          37.77      , -122.42      ]], shape=(13828, 8))

In [15]:
y_train

array([1.214, 3.637, 2.056, ..., 2.221, 2.835, 3.25 ], shape=(13828,))

In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score


In [17]:
df=pd.read_csv("linear_regression_dataset.csv")
df.head()

Feature1  Feature2   Feature3     Target
0 -2.509198  1.708780  25.340565  38.731756
1  9.014286  9.380854  37.572600  81.697219
2  4.639879  4.752119  35.948520  75.859955
3  1.973170 -2.884518  33.169037  76.893951
4 -6.879627 -4.492073  37.011635  60.665352

In [18]:
x=df[["Feature1","Feature2","Feature3"]]
y=df["Target"]

In [19]:
print(X.shape)
print(y.shape)


(20640, 8)
(500,)


In [20]:
df = pd.read_csv("linear_regression_dataset.csv")

X = df[["Feature1", "Feature2", "Feature3"]]
y = df["Target"]


In [21]:
print(X.shape)
print(y.shape)


(500, 3)
(500,)


In [22]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [23]:
model = LinearRegression()

In [24]:
model.fit(X_train, y_train)


LinearRegression()

In [25]:
print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)

Intercept: 5.491691681932814
Coefficients: [ 3.50784928 -2.11407914  1.78983297]


In [27]:
X_test

Feature1  Feature2   Feature3
361  2.865764 -3.776915  27.976456
73   6.309229 -5.989389  33.609986
374 -8.576227 -2.878189  24.869646
155 -5.158895 -5.648534  34.129515
104  8.151329 -0.039863  38.416957
..        ...       ...        ...
347 -9.093920 -8.512918  27.465036
86   4.592124 -7.575955  37.881984
75   4.580143  0.176318  25.465191
438  4.124845 -2.227513  31.889527
15  -6.331910 -2.996875  20.584946

[100 rows x 3 columns]

In [28]:
y_test

361     68.059343
73      91.447029
374     26.752506
155     57.588383
104    113.254416
          ...    
347     46.437005
86     111.609963
75      69.975721
438     83.098533
15      30.376797
Name: Target, Length: 100, dtype: float64

In [36]:
model.predict(X_test.iloc[0].values.reshape(1, -1))


array([73.60224023])

In [35]:
import warnings
warnings.filterwarnings('ignore')

In [37]:
model.predict(X_test.iloc[1].values.reshape(1,-1))

array([100.44181894])