In [6]:
import numpy as np

In [7]:
arr=np.array([])
arr

array([], dtype=float64)

In [8]:
type(arr)

numpy.ndarray

In [9]:
my_list=[1,2,3,4,5]
print(my_list)
print(type(my_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [10]:
a=np.array(my_list)

In [11]:
a

array([1, 2, 3, 4, 5])

In [12]:
type(a)

numpy.ndarray

In [13]:
my_list+[2,2,2]

[1, 2, 3, 4, 5, 2, 2, 2]

In [14]:
a.ndim

1

In [15]:
a.shape

(5,)

In [16]:
a.size

5

In [17]:
aa=[[1,2,3,4],[5,6,7,8],[8,9,10,11]]
aa

[[1, 2, 3, 4], [5, 6, 7, 8], [8, 9, 10, 11]]

In [18]:
type(aa)

list

In [19]:
b=np.array(aa)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 8,  9, 10, 11]])

In [20]:
b.ndim

2

In [21]:
b.dtype

dtype('int64')

In [22]:
type(b)

numpy.ndarray

In [23]:
b.size

12

In [24]:
arr1=np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
arr1.shape

(2, 2, 3)

In [26]:
arr1[1][1][2]

np.int64(12)

In [27]:
np.mean([1,2,3,4])

np.float64(2.5)

In [28]:
arr2=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]])

In [29]:
arr2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [30]:
arr2.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [31]:
desc_arr = np.sort(arr2.reshape(-1))[::-1]

In [32]:
desc_arr

array([16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [28]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [30]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [31]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [32]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.linspace(1,50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [34]:
np.linspace(1,10,2,retstep=True)

(array([ 1., 10.]), np.float64(9.0))

In [35]:


np.linspace(1,200,5,retstep=True)

(array([  1.  ,  50.75, 100.5 , 150.25, 200.  ]), np.float64(49.75))

In [36]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
a=np.ones((5,5))

In [38]:
bigger =np.array(a*5-2,dtype='int')
print(bigger)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


In [39]:
a/bigger

array([[0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333]])

In [40]:
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [41]:
1/arr1[1:]

array([[[0.14285714, 0.125     , 0.11111111],
        [0.1       , 0.09090909, 0.08333333]]])

In [42]:
import warnings
warnings.filterwarnings("ignore")


arr1=np.arange(20)
1/arr1

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [43]:
arr1+arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [44]:
aa=np.arange(10)

In [45]:
aa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
aa[0]=200

In [47]:
aa

array([200,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [48]:
arr3=arr1.copy()

In [49]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [50]:
arr3[10:]=100

In [51]:
arr3

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

In [52]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
np.random.rand(19) # std of normal distribution 

array([0.04642864, 0.86273354, 0.14896823, 0.96257342, 0.86504373,
       0.50461375, 0.10945183, 0.84743026, 0.89773353, 0.23795667,
       0.7057047 , 0.86831371, 0.48696994, 0.26730017, 0.19619811,
       0.12158149, 0.37217859, 0.16853932, 0.19836511])

In [34]:
np.random.rand(4,2)

array([[0.59342172, 0.26919926],
       [0.33873222, 0.50725376],
       [0.60464395, 0.5432945 ],
       [0.76012412, 0.06836235]])

In [55]:
np.random.rand(1,6)

array([[0.01759136, 0.21433111, 0.54383123, 0.89566088, 0.14368233,
        0.53459039]])

In [56]:
np.random.randint(1,6)

2

In [57]:
aaa=np.random.randn(50)
aaa

array([ 1.0098506 ,  1.05700549, -0.59483336, -0.13771869,  1.51106333,
       -1.41283473, -0.26159806, -0.33223635,  0.21863741, -1.29632291,
        0.26775457, -0.01732555, -0.1595553 , -0.2896093 , -2.12040994,
        1.13599566,  0.5541462 , -1.47225258, -0.50254578, -1.68489663,
       -0.05974715, -1.71006517,  0.85548937,  1.0704205 ,  0.31877973,
        0.09949852,  0.24975046,  1.11702402, -0.36629355, -0.66551818,
        0.9134994 ,  0.94422056,  0.81057791,  2.39559926,  0.32383805,
       -1.20461651, -0.15356216, -0.45865771,  0.03499519,  1.08741044,
        0.73845992, -0.02511674, -0.75029497,  1.31865462, -0.85081806,
       -0.39454837,  0.17811967, -1.28534419,  1.50423489,  1.19634058])

In [58]:
np.mean(aaa)

np.float64(0.05409288847014154)

In [59]:
np.median(aaa)

np.float64(0.0088348207708816)

In [60]:
np.std(aaa)

np.float64(0.9704531341855952)

In [61]:
np.var(aaa)

np.float64(0.941779285650645)

In [73]:
np.random.randint(1,7)

1

In [74]:
arr=np.random.randint(1,100,10)

In [75]:
arr

array([15, 75, 61, 31, 37, 86, 21, 57, 52, 86], dtype=int32)

In [76]:
arr.max()

np.int32(86)

In [77]:
arr.min()

np.int32(15)

In [78]:
arr.sum()

np.int64(521)

In [79]:
arr.argmax()

np.int64(5)

In [80]:
arr.argmin()

np.int64(0)

In [81]:
arrr=np.random.randint(1,200,20)

In [82]:
arrr

array([  6, 154, 167, 122,  14,  79, 117, 163,  58,  85,  36, 141, 122,
        65, 140, 122, 127,  50, 114, 149], dtype=int32)

In [83]:
arrr.min()

np.int32(6)

In [84]:
arrr.max()

np.int32(167)

In [85]:
arrr.argmax()

np.int64(2)

In [5]:
arrr.argmin()

NameError: name 'arrr' is not defined

In [87]:
arrr.reshape(5,4)

array([[  6, 154, 167, 122],
       [ 14,  79, 117, 163],
       [ 58,  85,  36, 141],
       [122,  65, 140, 122],
       [127,  50, 114, 149]], dtype=int32)

In [88]:
arr.ravel()

array([15, 75, 61, 31, 37, 86, 21, 57, 52, 86], dtype=int32)

In [89]:
arr.transpose()

array([15, 75, 61, 31, 37, 86, 21, 57, 52, 86], dtype=int32)

In [90]:
arrr

array([  6, 154, 167, 122,  14,  79, 117, 163,  58,  85,  36, 141, 122,
        65, 140, 122, 127,  50, 114, 149], dtype=int32)

In [92]:
arrr.reshape(5,4)

array([[  6, 154, 167, 122],
       [ 14,  79, 117, 163],
       [ 58,  85,  36, 141],
       [122,  65, 140, 122],
       [127,  50, 114, 149]], dtype=int32)

In [93]:
arr.transpose()

array([15, 75, 61, 31, 37, 86, 21, 57, 52, 86], dtype=int32)

In [94]:
arrrr=np.arange(20).reshape(5,4)

In [95]:
arrrr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [96]:
arrrr.transpose()

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])